In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

### Extract the crowdfunding.xlsx Data

In [2]:
# Read the data into a Pandas DataFrame
crowdfunding_info_df = pd.read_excel('Resources/crowdfunding.xlsx')
crowdfunding_info_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays

In [3]:
# Get a brief summary of the crowdfunding_info DataFrame.
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   contact_id               1000 non-null   int64
 2   company_name             1000 non-null   object
 3   blurb                    1000 non-null   object
 4   goal                     1000 non-null   int64
 5   pledged                  1000 non-null   int64
 6   outcome                  1000 non-null   object
 7   backers_count            1000 non-null   int64
 8   country                  1000 non-null   object
 9   currency                 1000 non-null   object
 10  launched_at              1000 non-null   int64
 11  deadline                 1000 non-null   int64
 12  staff_pick               1000 non-null   bool
 13  spotlight                1000 non-null   bool
 14  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(7), object(6)
memory usage: 103.6+ KB

### Create the Category and Subcategory DataFrames
---
**Create a Category DataFrame that has the following columns:**
- A "category_id" column that is numbered sequential form 1 to the length of the number of unique categories.
- A "category" column that has only the categories.

Export the DataFrame as a `category.csv` CSV file.

**Create a SubCategory DataFrame that has the following columns:**
- A "subcategory_id" column that is numbered sequential form 1 to the length of the number of unique subcategories.
- A "subcategory" column that has only the subcategories. 

Export the DataFrame as a `subcategory.csv` CSV file.

In [7]:
# Get the crowdfunding_info_df columns.
columns = crowdfunding_info_df.columns
print(columns)

Index(['cf_id', 'contact_id', 'company_name', 'blurb', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'launched_at',
       'deadline', 'staff_pick', 'spotlight', 'category & sub-category'],
      dtype='object')

In [9]:
# Display count of each category & sub-category
crowdfunding_info_df['category & sub-category'].value_counts()

theater/plays                    344
music/rock                        85
film & video/documentary          60
technology/web                    51
food/food trucks                  46
music/indie rock                  45
technology/wearables              45
photography/photography books     42
film & video/drama                37
games/video games                 35
film & video/animation            34
publishing/nonfiction             21
publishing/translations           21
music/electric music              18
music/jazz                        17
publishing/fiction                17
film & video/television           17
film & video/shorts               16
film & video/science fiction      14
games/mobile games                13
publishing/radio & podcasts        8
music/metal                        7
journalism/audio                   4
music/world music                  3
Name: category & sub-category, dtype: int64

In [12]:
# Assign the category and subcategory values to category and subcategory columns.
crowdfunding_info_df[['category','sub-category']] = crowdfunding_info_df['category & sub-category'].str.split('/',expand=True)
crowdfunding_info_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [20]:
# Get the unique categories and subcategories in separate lists.
categories = crowdfunding_info_df['category'].unique()
subcategories = crowdfunding_info_df['sub-category'].unique()

In [21]:
# Get the unique categories and subcategories in separate lists.
print(categories)
print(subcategories)

['food' 'music' 'technology' 'theater' 'film & video' 'publishing' 'games'
 'photography' 'journalism']
['food trucks' 'rock' 'web' 'plays' 'documentary' 'electric music' 'drama'
 'indie rock' 'wearables' 'nonfiction' 'animation' 'video games' 'shorts'
 'fiction' 'photography books' 'radio & podcasts' 'metal' 'jazz'
 'translations' 'television' 'mobile games' 'world music'
 'science fiction' 'audio']

In [22]:
# Get the number of distinct values in the categories and subcategories lists.
print(len(categories))
print(len(subcategories))

9
24

In [23]:
# Create numpy arrays from 1-9 for the categories and 1-24 for the subcategories.
category_ids = np.arange(1, 10)
subcategory_ids = np.arange(1, 25)

print(category_ids)
print(subcategory_ids)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

In [24]:
# Use a list comprehension to add "cat" to each category_id.
cat_ids = [f"cat{n}" for n in category_ids]

# Use a list comprehension to add "subcat" to each subcategory_id.    
scat_ids = [f"subcat{n}" for n in subcategory_ids]
    
print(cat_ids)
print(scat_ids)

['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9']
['subcat1', 'subcat2', 'subcat3', 'subcat4', 'subcat5', 'subcat6', 'subcat7', 'subcat8', 'subcat9', 'subcat10', 'subcat11', 'subcat12', 'subcat13', 'subcat14', 'subcat15', 'subcat16', 'subcat17', 'subcat18', 'subcat19', 'subcat20', 'subcat21', 'subcat22', 'subcat23', 'subcat24']

In [28]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.
category_df = pd.DataFrame({'category_id': cat_ids,
                            'category': categories})

# Create a category DataFrame with the subcategory_id array as the subcategory_id and subcategories list as the subcategory name. 
subcategory_df = pd.DataFrame({'subcategory_id': scat_ids,
                            'subcategory': subcategories})

In [29]:
category_df

  category_id      category
0        cat1          food
1        cat2         music
2        cat3    technology
3        cat4       theater
4        cat5  film & video
5        cat6    publishing
6        cat7         games
7        cat8   photography
8        cat9    journalism

In [30]:
subcategory_df

   subcategory_id        subcategory
0         subcat1        food trucks
1         subcat2               rock
2         subcat3                web
3         subcat4              plays
4         subcat5        documentary
5         subcat6     electric music
6         subcat7              drama
7         subcat8         indie rock
8         subcat9          wearables
9        subcat10         nonfiction
10       subcat11          animation
11       subcat12        video games
12       subcat13             shorts
13       subcat14            fiction
14       subcat15  photography books
15       subcat16   radio & podcasts
16       subcat17              metal
17       subcat18               jazz
18       subcat19       translations
19       subcat20         television
20       subcat21       mobile games
21       subcat22        world music
22       subcat23    science fiction
23       subcat24              audio

In [32]:
# Export categories_df and subcategories_df as CSV files.
category_df.to_csv("Resources/category.csv", index=False)
subcategory_df.to_csv("Resources/subcategory.csv", index=False)

### Campaign DataFrame
----
**Create a Campaign DataFrame that has the following columns:**
- The "cf_id" column.
- The "contact_id" column.
- The “company_name” column.
- The "blurb" column is renamed as "description."
- The "goal" column.
- The "goal" column is converted to a `float` datatype.
- The "pledged" column is converted to a `float` datatype. 
- The "backers_count" column. 
- The "country" column.
- The "currency" column.
- The "launched_at" column is renamed as "launch_date" and converted to a datetime format. 
- The "deadline" column is renamed as "end_date" and converted to a datetime format.
- The "category_id" with the unique number matching the “category_id” from the category DataFrame. 
- The "subcategory_id" with the unique number matching the “subcategory_id” from the subcategory DataFrame.
- And, create a column that contains the unique four-digit contact ID number from the `contact.xlsx` file.
 

Then export the DataFrame as a `campaign.csv` CSV file.

In [33]:
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df. 
campaign_df = crowdfunding_info_df.copy()
campaign_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [34]:
# Rename the blurb, launched_at, and deadline columns.
campaign_df = campaign_df.rename(columns={'blurb': 'description',
                                          'launched_at': 'launched_date',
                                          'deadline': 'end_date'})

campaign_df.head()

In [37]:
# Convert the goal and pledged columns to a `float` data type.
campaign_df = campaign_df.astype({"goal": "float",
								"pledged": "float"})

campaign_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [39]:
# Check the datatypes
campaign_df.dtypes

cf_id                        int64
contact_id                   int64
company_name                object
description                 object
goal                       float64
pledged                    float64
outcome                     object
backers_count                int64
country                     object
currency                    object
launched_date                int64
end_date                     int64
staff_pick                    bool
spotlight                     bool
category & sub-category     object
category                    object
sub-category                object
dtype: object

In [40]:
# Format the launched_date and end_date columns to datetime format
from datetime import datetime as dt

campaign_df['launched_date'] = pd.to_datetime(campaign_df['launched_date'], unit='s').dt.strftime('%Y-%m-%d')
campaign_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,1629694800,False,False,theater/plays,theater,plays

In [41]:
campaign_df['end_date'] = pd.to_datetime(campaign_df['end_date'], unit='s').dt.strftime('%Y-%m-%d')
campaign_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,2021-05-25,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,2021-12-30,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,2022-01-17,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,2021-08-23,False,False,theater/plays,theater,plays

In [45]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.
campaign_merged_df = campaign_df.merge(category_df, on='category', how='inner')
campaign_merged_df = campaign_merged_df.merge(subcategory_df, left_on='sub-category', right_on='subcategory', how='inner')

campaign_merged_df.tail(10)

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,sub-category,category_id,subcategory_id,subcategory
990,399,5983,"Dixon, Perez and Banks",Re-engineered encompassing definition,8300.0,2111.0,failed,57,CA,CAD,2021-12-29,2022-01-16,False,False,photography/photography books,photography,photography books,cat8,subcat15,photography books
991,1378,2873,Clements Ltd,Persistent bandwidth-monitored framework,3700.0,1343.0,failed,52,US,USD,2020-07-07,2021-07-27,False,False,photography/photography books,photography,photography books,cat8,subcat15,photography books
992,806,2961,Walter Inc,Streamlined 5thgeneration intranet,10000.0,8142.0,failed,263,AU,AUD,2020-12-20,2021-01-31,False,False,photography/photography books,photography,photography books,cat8,subcat15,photography books
993,1563,3043,"Sanders, Farley and Huffman",Cross-group clear-thinking task-force,172000.0,55805.0,failed,1691,US,USD,2021-04-08,2021-12-18,True,False,photography/photography books,photography,photography books,cat8,subcat15,photography books
994,1951,6013,Rodriguez-Robinson,Ergonomic methodical hub,5900.0,4997.0,failed,114,IT,EUR,2021-07-23,2021-11-25,False,True,photography/photography books,photography,photography books,cat8,subcat15,photography books
995,461,3521,Erickson-Rogers,De-engineered even-keeled definition,9800.0,7608.0,canceled,75,IT,EUR,2021-07-03,2021-07-08,False,True,photography/photography books,photography,photography books,cat8,subcat15,photography books
996,1095,3565,Young and Sons,Innovative disintermediate encryption,2400.0,4596.0,successful,144,US,USD,2020-11-28,2021-02-28,False,False,journalism/audio,journalism,audio,cat9,subcat24,audio
997,1388,4517,Valenzuela-Cook,Total incremental productivity,6700.0,7496.0,successful,300,US,USD,2021-01-04,2021-10-04,False,False,journalism/audio,journalism,audio,cat9,subcat24,audio
998,2448,2389,Little Ltd,Decentralized bandwidth-monitored ability,6900.0,12155.0,successful,419,US,USD,2021-01-25,2021-04-18,False,False,journalism/audio,journalism,audio,cat9,subcat24,audio
999,602,2153,Giles-Smith,Right-sized web-enabled intranet,9700.0,11929.0,successful,331,US,USD,2022-02-01,2022-02-16,False,False,journalism/audio,journalism,audio,cat9,subcat24,audio

In [46]:
# List columns
campaign_merged_df.columns

Index(['cf_id', 'contact_id', 'company_name', 'description', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'launched_date',
       'end_date', 'staff_pick', 'spotlight', 'category & sub-category',
       'category', 'sub-category', 'category_id', 'subcategory_id',
       'subcategory'],
      dtype='object')

In [50]:
# Drop unwanted columns
columns_to_drop = ['category & sub-category','category', 'sub-category','subcategory']
campaign_merged_df = campaign_merged_df.drop(columns_to_drop, axis=1)

campaign_merged_df.head()

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category_id,subcategory_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,False,False,cat1,subcat1
1,1175,2288,Werner-Bryant,Virtual uniform frame,1800.0,7991.0,successful,222,US,USD,2020-06-20,2021-01-30,False,False,cat1,subcat1
2,873,2067,Stewart LLC,Cloned bi-directional architecture,1300.0,12047.0,successful,113,US,USD,2020-11-29,2021-06-11,False,False,cat1,subcat1
3,2568,5989,Castillo-Carey,Cross-platform solution-oriented process improvement,142400.0,21307.0,failed,296,US,USD,2020-05-05,2021-05-30,False,False,cat1,subcat1
4,1211,3307,"Wright, Hartman and Yu",User-friendly tertiary array,3300.0,12437.0,successful,131,US,USD,2021-01-29,2021-02-13,False,False,cat1,subcat1

In [51]:
# List columns
campaign_merged_df.columns

Index(['cf_id', 'contact_id', 'company_name', 'description', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'launched_date',
       'end_date', 'staff_pick', 'spotlight', 'category_id', 'subcategory_id'],
      dtype='object')

In [53]:
# Additional columns to drop
columns_to_drop = ['staff_pick','spotlight']
campaign_merged_df = campaign_merged_df.drop(columns_to_drop, axis=1)

# List columns
campaign_merged_df.columns

Index(['cf_id', 'contact_id', 'company_name', 'description', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'launched_date',
       'end_date', 'category_id', 'subcategory_id'],
      dtype='object')

In [55]:
# Export the DataFrame as a CSV file. 
campaign_merged_df.to_csv("Resources/campaign_BChamot.csv", index=False)

### Extract the contacts.xlsx Data.

In [114]:
# Read the data into a Pandas DataFrame. Use the `header=2` parameter when reading in the data.
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=3)
contact_info_df.head()

                                                                                contact_info
0   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
1          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
2            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
3  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}
4        {"contact_id": 2199, "name": "Samuel Sorgatz", "email": "samuel.sorgatz@gmail.com"}

### Create the Contacts DataFrame 
---
**Create a Contacts DataFrame that has the following columns:**
- A column named "contact_id"  that contains the unique number of the contact person.
- A column named "first_name" that contains the first name of the contact person.
- A column named "last_name" that contains the first name of the contact person.
- A column named "email" that contains the email address of the contact person

Then export the DataFrame as a `contacts.csv` CSV file.

### Option 1: Use Pandas to create the contacts DataFrame.

In [115]:
# Iterate through the contact_info_df and convert each row to a dictionary.
# https://www.geeksforgeeks.org/python-convert-string-dictionary-to-dictionary/
import json
dict_values = []

for index, row in contact_info_df.iterrows():
    in_string = str(row['contact_info'])
    dict_values.append(json.loads(in_string))

# Print out the list of values for each row.
print(dict_values)

[{'contact_id': 4661, 'name': 'Cecilia Velasco', 'email': 'cecilia.velasco@rodrigues.fr'}, {'contact_id': 3765, 'name': 'Mariana Ellis', 'email': 'mariana.ellis@rossi.org'}, {'contact_id': 4187, 'name': 'Sofie Woods', 'email': 'sofie.woods@riviere.com'}, {'contact_id': 4941, 'name': 'Jeanette Iannotti', 'email': 'jeanette.iannotti@yahoo.com'}, {'contact_id': 2199, 'name': 'Samuel Sorgatz', 'email': 'samuel.sorgatz@gmail.com'}, {'contact_id': 5650, 'name': 'Socorro Luna', 'email': 'socorro.luna@hotmail.com'}, {'contact_id': 5889, 'name': 'Carolina Murray', 'email': 'carolina.murray@knight.com'}, {'contact_id': 4842, 'name': 'Kayla Moon', 'email': 'kayla.moon@yahoo.de'}, {'contact_id': 3280, 'name': 'Ariadna Geisel', 'email': 'ariadna.geisel@rangel.com'}, {'contact_id': 5468, 'name': 'Danielle Ladeck', 'email': 'danielle.ladeck@scalfaro.net'}, {'contact_id': 3064, 'name': 'Tatiana Thompson', 'email': 'tatiana.thompson@hunt.net'}, {'contact_id': 4904, 'name': 'Caleb Benavides', 'email': 'caleb.benavides@rubio.com'}, {'contact_id': 1299, 'name': 'Sandra Hardy', 'email': 'sandra.hardy@web.de'}, {'contact_id': 5602, 'name': 'Lotti Morris', 'email': 'lotti.morris@yahoo.co.uk'}, {'contact_id': 5753, 'name': 'Reinhilde White', 'email': 'reinhilde.white@voila.fr'}, {'contact_id': 4495, 'name': 'Kerry Patel', 'email': 'kerry.patel@hutchinson.com'}, {'contact_id': 4269, 'name': 'Sophie Antoine', 'email': 'sophie.antoine@andersen.com'}, {'contact_id': 2226, 'name': 'Martha Girard', 'email': 'martha.girard@web.de'}, {'contact_id': 1558, 'name': 'Stephanie King', 'email': 'stephanie.king@cervantes.com'}, {'contact_id': 2307, 'name': 'Amanda Palmer', 'email': 'amanda.palmer@didier.fr'}, {'contact_id': 2900, 'name': 'Lina Alcala', 'email': 'lina.alcala@vespa.net'}, {'contact_id': 5695, 'name': 'Itzel Murphy', 'email': 'itzel.murphy@muelichen.de'}, {'contact_id': 5708, 'name': 'Filippo Parry', 'email': 'filippo.parry@live.com'}, {'contact_id': 1663, 'name': 'Katelyn Cole', 'email': 'katelyn.cole@fiebig.com'}, {'contact_id': 3605, 'name': 'Brian Novak', 'email': 'brian.novak@ford.net'}, {'contact_id': 4678, 'name': 'Cilly Gay', 'email': 'cilly.gay@callegaro.it'}, {'contact_id': 2251, 'name': 'Yolanda Snyder', 'email': 'yolanda.snyder@gmx.de'}, {'contact_id': 6202, 'name': 'Evelin Odonnell', 'email': 'evelin.odonnell@ibarra.net'}, {'contact_id': 3715, 'name': 'Ingeborg Alba', 'email': 'ingeborg.alba@hotmail.com'}, {'contact_id': 4242, 'name': 'Marina Madrid', 'email': 'marina.madrid@galarza-alba.com'}, {'contact_id': 4326, 'name': 'Sheila Goodwin', 'email': 'sheila.goodwin@yahoo.com'}, {'contact_id': 5560, 'name': 'Valeria Rich', 'email': 'valeria.rich@turchetta-mondadori.it'}, {'contact_id': 4002, 'name': 'Dustin Camacho', 'email': 'dustin.camacho@rhodes.org.au'}, {'contact_id': 3813, 'name': 'Amalia Marenzio', 'email': 'amalia.marenzio@grupo.com'}, {'contact_id': 5336, 'name': 'Gian Long', 'email': 'gian.long@hotmail.com'}, {'contact_id': 4994, 'name': 'Stewart Hunt', 'email': 'stewart.hunt@anderson-vargas.biz'}, {'contact_id': 1471, 'name': 'Greca Ruiz', 'email': 'greca.ruiz@carr.co.uk'}, {'contact_id': 4482, 'name': 'Gerald Olivera', 'email': 'gerald.olivera@outlook.com'}, {'contact_id': 3241, 'name': 'Jaqueline Wallace', 'email': 'jaqueline.wallace@gmail.com'}, {'contact_id': 3477, 'name': 'John Lane', 'email': 'john.lane@gregoire.fr'}, {'contact_id': 2265, 'name': 'Pero Joly', 'email': 'pero.joly@bernard.net'}, {'contact_id': 5911, 'name': 'Chad Turner', 'email': 'chad.turner@gmail.com'}, {'contact_id': 2288, 'name': 'Adam Zavala', 'email': 'adam.zavala@guichard.fr'}, {'contact_id': 4064, 'name': 'Tyler Rivera', 'email': 'tyler.rivera@guajardo-ozuna.com'}, {'contact_id': 1294, 'name': 'Jens Graham', 'email': 'jens.graham@jones-buckley.com'}, {'contact_id': 5008, 'name': 'Virginia Caetani', 'email': 'virginia.caetani@sosa.biz'}, {'contact_id': 3604, 'name': 'Martino Wagner', 'email': 'martino.wagner@laposte.net'}, {'contact_id': 3263, 'name': 'Martin Meyer', 'email': 'martin.meyer@davis.co.uk'}, {'contact_id': 5631, 'name': 'Marguerite Walls', 'email': 'marguerite.walls@martinez.fr'}, {'contact_id': 2851, 'name': 'Peter Vogt', 'email': 'peter.vogt@yahoo.com'}, {'contact_id': 3714, 'name': 'Nicholas Christian', 'email': 'nicholas.christian@hotmail.de'}, {'contact_id': 1664, 'name': 'Susi Steinberg', 'email': 'susi.steinberg@preiss.com'}, {'contact_id': 5027, 'name': 'Tammy Ramazzotti', 'email': 'tammy.ramazzotti@gmail.com'}, {'contact_id': 3070, 'name': 'Abdul Thomas', 'email': 'abdul.thomas@vasari.com'}, {'contact_id': 4248, 'name': 'Justin Luxardo', 'email': 'justin.luxardo@googlemail.com'}, {'contact_id': 2034, 'name': 'Antonio Gibson', 'email': 'antonio.gibson@faust.net'}, {'contact_id': 4085, 'name': 'Jeremy Gomez', 'email': 'jeremy.gomez@oconnor.org'}, {'contact_id': 3569, 'name': 'Raymond Solorzano', 'email': 'raymond.solorzano@gmail.com'}, {'contact_id': 3889, 'name': 'Flora Harris', 'email': 'flora.harris@hotmail.com.au'}, {'contact_id': 3136, 'name': 'Cheryl Boyd', 'email': 'cheryl.boyd@segni.it'}, {'contact_id': 2103, 'name': 'Rhys Leiva', 'email': 'rhys.leiva@gmx.de'}, {'contact_id': 2329, 'name': 'Mariano Prieto', 'email': 'mariano.prieto@vodafone.it'}, {'contact_id': 3325, 'name': 'Laurie Fibonacci', 'email': 'laurie.fibonacci@gmail.com'}, {'contact_id': 3131, 'name': 'David Rudolph', 'email': 'david.rudolph@nelson.com'}, {'contact_id': 4995, 'name': 'Bryan Ross', 'email': 'bryan.ross@yahoo.com'}, {'contact_id': 3631, 'name': 'Ubaldo Brown', 'email': 'ubaldo.brown@philippe.com'}, {'contact_id': 5373, 'name': 'Clelia Faulkner', 'email': 'clelia.faulkner@hotmail.com'}, {'contact_id': 3126, 'name': 'Sara Erickson', 'email': 'sara.erickson@yahoo.de'}, {'contact_id': 2194, 'name': 'Rupert Valle', 'email': 'rupert.valle@filogamo.it'}, {'contact_id': 2906, 'name': 'Puccio Kitzmann', 'email': 'puccio.kitzmann@yahoo.com'}, {'contact_id': 2611, 'name': 'Thomas Hutchinson', 'email': 'thomas.hutchinson@gmx.de'}, {'contact_id': 2374, 'name': 'Abelardo Castro', 'email': 'abelardo.castro@gmail.com'}, {'contact_id': 3254, 'name': 'Greco Walker', 'email': 'greco.walker@yahoo.com'}, {'contact_id': 3571, 'name': 'Miranda Lacombe', 'email': 'miranda.lacombe@longoria-vanegas.net'}, {'contact_id': 2812, 'name': 'Diana Schuchhardt', 'email': 'diana.schuchhardt@libero.it'}, {'contact_id': 3961, 'name': 'Stacey Knox', 'email': 'stacey.knox@corporacin.com'}, {'contact_id': 3872, 'name': 'Glen Faivre', 'email': 'glen.faivre@yahoo.com'}, {'contact_id': 4736, 'name': 'Andrew Torres', 'email': 'andrew.torres@ruiz-torres.org'}, {'contact_id': 5119, 'name': 'Denny Fritz', 'email': 'denny.fritz@despacho.biz'}, {'contact_id': 5725, 'name': 'Martyn Caldera', 'email': 'martyn.caldera@hotmail.co.uk'}, {'contact_id': 4037, 'name': 'Abigail Foster', 'email': 'abigail.foster@taylor.net'}, {'contact_id': 2109, 'name': 'Anthony Hauffer', 'email': 'anthony.hauffer@tlustek.org'}, {'contact_id': 3283, 'name': 'Roger Gerlach', 'email': 'roger.gerlach@may-mitchell.co.uk'}, {'contact_id': 6181, 'name': 'Christopher Poirier', 'email': 'christopher.poirier@hotmail.com'}, {'contact_id': 3251, 'name': 'Branka Traore', 'email': 'branka.traore@jacobi.com'}, {'contact_id': 3443, 'name': 'Briana Etienne', 'email': 'briana.etienne@bishop-coates.com'}, {'contact_id': 2988, 'name': 'Brandon Olson', 'email': 'brandon.olson@prince-moreno.net'}, {'contact_id': 1673, 'name': 'Celia Ungaretti', 'email': 'celia.ungaretti@fox.com'}, {'contact_id': 2085, 'name': 'Barbara Guibert', 'email': 'barbara.guibert@casares-sanches.com'}, {'contact_id': 1672, 'name': 'Daniela Bell', 'email': 'daniela.bell@vollbrecht.org'}, {'contact_id': 4426, 'name': 'Phyllis Gurule', 'email': 'phyllis.gurule@rodriguez-pham.com'}, {'contact_id': 3211, 'name': 'Alejandra Joseph', 'email': 'alejandra.joseph@escalante-abrego.biz'}, {'contact_id': 3190, 'name': 'Giulio Bohlander', 'email': 'giulio.bohlander@dbmail.com'}, {'contact_id': 2081, 'name': 'Amber Weller', 'email': 'amber.weller@toso.eu'}, {'contact_id': 3185, 'name': 'Mary Etzold', 'email': 'mary.etzold@conrad-harrison.com'}, {'contact_id': 5044, 'name': 'Amy Georges', 'email': 'amy.georges@raedel.de'}, {'contact_id': 1883, 'name': 'Jennifer Giraud', 'email': 'jennifer.giraud@yahoo.com'}, {'contact_id': 2067, 'name': 'Rosie Peltier', 'email': 'rosie.peltier@voila.fr'}, {'contact_id': 4604, 'name': 'Oreste Ward', 'email': 'oreste.ward@proyectos.com'}, {'contact_id': 3203, 'name': 'Luis Edwards', 'email': 'luis.edwards@live.com'}, {'contact_id': 5758, 'name': 'Fiona Griffiths', 'email': 'fiona.griffiths@curatoli-verdone.it'}, {'contact_id': 5755, 'name': 'Sally Raya', 'email': 'sally.raya@tarchetti.it'}, {'contact_id': 5150, 'name': 'Carolyn Charpentier', 'email': 'carolyn.charpentier@hotmail.de'}, {'contact_id': 4181, 'name': 'Nathalie Alvarez', 'email': 'nathalie.alvarez@live.com'}, {'contact_id': 3006, 'name': 'Abril Lowery', 'email': 'abril.lowery@novak.net'}, {'contact_id': 4865, 'name': 'Ottone Sullivan', 'email': 'ottone.sullivan@hussain-kaur.com'}, {'contact_id': 2862, 'name': 'Esmeralda Sollima', 'email': 'esmeralda.sollima@visintini.it'}, {'contact_id': 6070, 'name': 'Silvia Gierschner', 'email': 'silvia.gierschner@tele2.it'}, {'contact_id': 5300, 'name': 'Kyle Cunningham', 'email': 'kyle.cunningham@voila.fr'}, {'contact_id': 3486, 'name': 'Anel Carpentier', 'email': 'anel.carpentier@klein-joseph.org'}, {'contact_id': 5989, 'name': 'Sarah Davis', 'email': 'sarah.davis@david.com'}, {'contact_id': 2849, 'name': 'Luke Klein', 'email': 'luke.klein@hotmail.com'}, {'contact_id': 1612, 'name': 'Gudrun Mueller', 'email': 'gudrun.mueller@dillon-fuller.info'}, {'contact_id': 3307, 'name': 'Melissa Canali', 'email': 'melissa.canali@libero.it'}, {'contact_id': 5288, 'name': 'Gabrielle Ayala', 'email': 'gabrielle.ayala@hotmail.com'}, {'contact_id': 6026, 'name': 'Laura Buckley', 'email': 'laura.buckley@ryan.org'}, {'contact_id': 2212, 'name': 'Wilfrido Lorch', 'email': 'wilfrido.lorch@leclerc.fr'}, {'contact_id': 4591, 'name': 'Robert Bruder', 'email': 'robert.bruder@manzoni.com'}, {'contact_id': 2771, 'name': 'Phillip Soliz', 'email': 'phillip.soliz@outlook.com'}, {'contact_id': 5682, 'name': 'Alex Smith', 'email': 'alex.smith@fournier.fr'}, {'contact_id': 5368, 'name': 'Jessica Martinez', 'email': 'jessica.martinez@salieri.com'}, {'contact_id': 3706, 'name': 'Kelly Carter', 'email': 'kelly.carter@hotmail.com.au'}, {'contact_id': 4034, 'name': 'Ahmad Sosa', 'email': 'ahmad.sosa@gmail.com'}, {'contact_id': 3209, 'name': 'Toralf Iglesias', 'email': 'toralf.iglesias@borrego.com'}, {'contact_id': 2384, 'name': 'Irene Anichini', 'email': 'irene.anichini@yahoo.com'}, {'contact_id': 3074, 'name': 'Alicia Cainero', 'email': 'alicia.cainero@yahoo.com'}, {'contact_id': 2031, 'name': 'Tracey Laboy', 'email': 'tracey.laboy@bell.biz'}, {'contact_id': 5873, 'name': 'Donald Reynaud', 'email': 'donald.reynaud@green.edu.au'}, {'contact_id': 5501, 'name': 'Venancio Stadelmann', 'email': 'venancio.stadelmann@gmx.de'}, {'contact_id': 3489, 'name': 'Seth Olivier', 'email': 'seth.olivier@yahoo.com'}, {'contact_id': 4210, 'name': 'Dennis Boaga', 'email': 'dennis.boaga@gmx.de'}, {'contact_id': 6151, 'name': 'Pedro Wilson', 'email': 'pedro.wilson@outlook.com'}, {'contact_id': 6047, 'name': 'Roland Weihmann', 'email': 'roland.weihmann@gmail.com'}, {'contact_id': 5445, 'name': 'Hector Morrison', 'email': 'hector.morrison@web.de'}, {'contact_id': 5493, 'name': 'Evangelos Peters', 'email': 'evangelos.peters@sanchez.net'}, {'contact_id': 6036, 'name': 'Gerardo Hamilton', 'email': 'gerardo.hamilton@libero.it'}, {'contact_id': 2368, 'name': 'Meta Cuzzocrea', 'email': 'meta.cuzzocrea@howard-jensen.org'}, {'contact_id': 1501, 'name': 'Alma Raymond', 'email': 'alma.raymond@tin.it'}, {'contact_id': 4351, 'name': 'Kathleen Solimena', 'email': 'kathleen.solimena@wallace.biz'}, {'contact_id': 3096, 'name': 'Zacharie Cordier', 'email': 'zacharie.cordier@gmail.com'}, {'contact_id': 6162, 'name': 'Riza Techer', 'email': 'riza.techer@yahoo.com'}, {'contact_id': 1433, 'name': 'Enrique Guillen', 'email': 'enrique.guillen@hotmail.co.uk'}, {'contact_id': 2720, 'name': 'Tristan Weeks', 'email': 'tristan.weeks@pena.com'}, {'contact_id': 5251, 'name': 'Natalie Lerma', 'email': 'natalie.lerma@boucher.com'}, {'contact_id': 1797, 'name': 'Rodney Hamon', 'email': 'rodney.hamon@hotmail.com'}, {'contact_id': 1656, 'name': 'Adalberto Lombardo', 'email': 'adalberto.lombardo@sfr.fr'}, {'contact_id': 1346, 'name': 'Florencia Querini', 'email': 'florencia.querini@gmail.com'}, {'contact_id': 2989, 'name': 'Liam Rolland', 'email': 'liam.rolland@yahoo.fr'}, {'contact_id': 5629, 'name': 'Ian Kelly', 'email': 'ian.kelly@reeves.com.au'}, {'contact_id': 3456, 'name': 'Mehdi Todd', 'email': 'mehdi.todd@web.de'}, {'contact_id': 3229, 'name': 'Rembrandt Liguori', 'email': 'rembrandt.liguori@davis.org'}, {'contact_id': 2277, 'name': 'Irmi Schweitzer', 'email': 'irmi.schweitzer@ozuna.com'}, {'contact_id': 1276, 'name': 'Gioffre Stein', 'email': 'gioffre.stein@hotmail.com.au'}, {'contact_id': 3694, 'name': 'Frida Villarreal', 'email': 'frida.villarreal@hotmail.de'}, {'contact_id': 2260, 'name': 'Steffen Mangold', 'email': 'steffen.mangold@paul.net'}, {'contact_id': 5374, 'name': 'Elias Marin', 'email': 'elias.marin@herve.net'}, {'contact_id': 4420, 'name': 'Roman Gonzalez', 'email': 'roman.gonzalez@anderson.net'}, {'contact_id': 3849, 'name': 'Reina Middleton', 'email': 'reina.middleton@hotmail.com'}, {'contact_id': 1638, 'name': 'Sandro Moran', 'email': 'sandro.moran@hotmail.de'}, {'contact_id': 5230, 'name': 'Gebhard Thanel', 'email': 'gebhard.thanel@gmail.com'}, {'contact_id': 1763, 'name': 'Antonino Bolander', 'email': 'antonino.bolander@gmail.com'}, {'contact_id': 4323, 'name': 'Karl Trevisani', 'email': 'karl.trevisani@anguissola.it'}, {'contact_id': 5256, 'name': 'Silvester Brookes', 'email': 'silvester.brookes@franco.org'}, {'contact_id': 4836, 'name': 'Octavio Pratt', 'email': 'octavio.pratt@web.de'}, {'contact_id': 5981, 'name': 'Rebecca Greer', 'email': 'rebecca.greer@hotmail.com'}, {'contact_id': 1463, 'name': 'Pierina Gaggini', 'email': 'pierina.gaggini@free.fr'}, {'contact_id': 4577, 'name': 'Robin Schleich', 'email': 'robin.schleich@rogers-barrera.biz'}, {'contact_id': 4951, 'name': 'Sergio Abbott', 'email': 'sergio.abbott@moore.net.au'}, {'contact_id': 3567, 'name': 'Gilberto Evans', 'email': 'gilberto.evans@salcedo-archuleta.net'}, {'contact_id': 5475, 'name': 'James Elliott', 'email': 'james.elliott@gmail.com'}, {'contact_id': 2114, 'name': 'Timoteo Bolnbach', 'email': 'timoteo.bolnbach@laboratorios.com'}, {'contact_id': 5216, 'name': 'Tonino Stanley', 'email': 'tonino.stanley@hotmail.com'}, {'contact_id': 1665, 'name': 'Margaretha Murialdo', 'email': 'margaretha.murialdo@meunier.com'}, {'contact_id': 6051, 'name': 'Bianca Drubin', 'email': 'bianca.drubin@libero.it'}, {'contact_id': 3983, 'name': 'Kaylee Hoffmann', 'email': 'kaylee.hoffmann@poulain.com'}, {'contact_id': 2966, 'name': 'Teresa Vecellio', 'email': 'teresa.vecellio@yahoo.com'}, {'contact_id': 4478, 'name': 'Emine Tacchini', 'email': 'emine.tacchini@dbmail.com'}, {'contact_id': 4238, 'name': 'Dawn Cortez', 'email': 'dawn.cortez@gmail.com'}, {'contact_id': 4404, 'name': 'Emily Cundari', 'email': 'emily.cundari@clark.com.au'}, {'contact_id': 5666, 'name': 'Eleanor Hall', 'email': 'eleanor.hall@hotmail.com'}, {'contact_id': 3691, 'name': 'Monique Delgadillo', 'email': 'monique.delgadillo@hotmail.co.uk'}, {'contact_id': 2703, 'name': 'Arnaude Warner', 'email': 'arnaude.warner@gmail.com'}, {'contact_id': 4253, 'name': 'Jason Howell', 'email': 'jason.howell@gmx.de'}, {'contact_id': 5652, 'name': 'Nicole Mccullough', 'email': 'nicole.mccullough@hall.com'}, {'contact_id': 3279, 'name': 'Rosmarie Esquibel', 'email': 'rosmarie.esquibel@bouygtel.fr'}, {'contact_id': 3233, 'name': 'Leonor Ferreira', 'email': 'leonor.ferreira@gmail.com'}, {'contact_id': 3017, 'name': 'Brett Jones', 'email': 'brett.jones@alice.it'}, {'contact_id': 3482, 'name': 'Nino Bien', 'email': 'nino.bien@gmail.com'}, {'contact_id': 2166, 'name': 'Jemma Tate', 'email': 'jemma.tate@hotmail.de'}, {'contact_id': 4146, 'name': 'Denis Rogers', 'email': 'denis.rogers@poste.it'}, {'contact_id': 2651, 'name': 'Vanesa Khan', 'email': 'vanesa.khan@voila.fr'}, {'contact_id': 1409, 'name': 'Victoria Ojeda', 'email': 'victoria.ojeda@doehn.com'}, {'contact_id': 3717, 'name': 'Eugenio Martin', 'email': 'eugenio.martin@yahoo.de'}, {'contact_id': 3963, 'name': 'Nancy Hayes', 'email': 'nancy.hayes@hotmail.com'}, {'contact_id': 2152, 'name': 'Lara Jacob', 'email': 'lara.jacob@buckley.org'}, {'contact_id': 2974, 'name': 'Gino Hernandez', 'email': 'gino.hernandez@covarrubias.com'}, {'contact_id': 1268, 'name': 'Vicente Tijerina', 'email': 'vicente.tijerina@montanariello.com'}, {'contact_id': 1822, 'name': 'Michele Brambilla', 'email': 'michele.brambilla@yahoo.com'}, {'contact_id': 5066, 'name': 'Dana Ritacca', 'email': 'dana.ritacca@gmail.com'}, {'contact_id': 5075, 'name': 'Mitchell Bachmann', 'email': 'mitchell.bachmann@suarez-cruz.com'}, {'contact_id': 3855, 'name': 'Vincenza Key', 'email': 'vincenza.key@adams.com'}, {'contact_id': 5923, 'name': 'Salvador Gaillard', 'email': 'salvador.gaillard@yahoo.de'}, {'contact_id': 1867, 'name': 'Diane Rogner', 'email': 'diane.rogner@kelly.co.uk'}, {'contact_id': 4376, 'name': 'Josette Laine', 'email': 'josette.laine@saracino-parisi.net'}, {'contact_id': 2785, 'name': 'Courtney Fiebig', 'email': 'courtney.fiebig@doerschner.com'}, {'contact_id': 5884, 'name': 'Hugues Oliver', 'email': 'hugues.oliver@stiffel.com'}, {'contact_id': 2441, 'name': 'Espartaco Willis', 'email': 'espartaco.willis@hotmail.com'}, {'contact_id': 1243, 'name': 'Flavia Yoder', 'email': 'flavia.yoder@hotmail.de'}, {'contact_id': 3411, 'name': 'Casey Flores', 'email': 'casey.flores@baggio.org'}, {'contact_id': 2467, 'name': 'Calogero Cross', 'email': 'calogero.cross@mercantini.it'}, {'contact_id': 1850, 'name': 'Charles Begum', 'email': 'charles.begum@laboratorios.info'}, {'contact_id': 2604, 'name': 'Adina Pollard', 'email': 'adina.pollard@outlook.com'}, {'contact_id': 1693, 'name': 'Natasha Lara', 'email': 'natasha.lara@outlook.com'}, {'contact_id': 2969, 'name': 'Benita Pottier', 'email': 'benita.pottier@sfr.fr'}, {'contact_id': 1544, 'name': 'Elizabeth Valdivia', 'email': 'elizabeth.valdivia@gmail.com'}, {'contact_id': 4149, 'name': 'Mattia Huet', 'email': 'mattia.huet@aol.de'}, {'contact_id': 3463, 'name': 'Geza Howard', 'email': 'geza.howard@voila.fr'}, {'contact_id': 2939, 'name': 'Lauren Guillaume', 'email': 'lauren.guillaume@sorgatz.org'}, {'contact_id': 2202, 'name': 'Joanna Baxter', 'email': 'joanna.baxter@bruce-wright.com'}, {'contact_id': 1728, 'name': 'Tracy Metz', 'email': 'tracy.metz@bryant.info'}, {'contact_id': 5362, 'name': 'Birgit Pena', 'email': 'birgit.pena@armellini.it'}, {'contact_id': 4840, 'name': 'Elvira Papafava', 'email': 'elvira.papafava@ifrance.com'}, {'contact_id': 2955, 'name': 'Ernest Delorme', 'email': 'ernest.delorme@dowerg.de'}, {'contact_id': 5354, 'name': 'Christy Grossi', 'email': 'christy.grossi@alarcon-tafoya.com'}, {'contact_id': 3847, 'name': 'Hermelinda Olmos', 'email': 'hermelinda.olmos@portillo.com'}, {'contact_id': 3025, 'name': 'Herbert Fraser', 'email': 'herbert.fraser@holloway.org.au'}, {'contact_id': 1615, 'name': 'Giancarlo Heydrich', 'email': 'giancarlo.heydrich@hotmail.com'}, {'contact_id': 5154, 'name': 'Constance Maldonado', 'email': 'constance.maldonado@spiess.net'}, {'contact_id': 5005, 'name': 'Giampiero Carlier', 'email': 'giampiero.carlier@hotmail.com'}, {'contact_id': 1349, 'name': 'Carlo Jacquot', 'email': 'carlo.jacquot@hotmail.com'}, {'contact_id': 3670, 'name': 'Gabriel Robles', 'email': 'gabriel.robles@yahoo.com'}, {'contact_id': 2912, 'name': 'Gerd Gunpf', 'email': 'gerd.gunpf@gmail.com'}, {'contact_id': 4336, 'name': 'Ashley Hellwig

In [116]:
# Iterate through the contact_info_df and convert each row to a dictionary.
contact_info = pd.DataFrame(dict_values)
contact_info.head()

   contact_id               name                         email
0        4661    Cecilia Velasco  cecilia.velasco@rodrigues.fr
1        3765      Mariana Ellis       mariana.ellis@rossi.org
2        4187        Sofie Woods       sofie.woods@riviere.com
3        4941  Jeanette Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel Sorgatz      samuel.sorgatz@gmail.com

In [117]:
# Check the datatypes.
contact_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   contact_id  1000 non-null   int64
 1   name        1000 non-null   object
 2   email       1000 non-null   object
dtypes: int64(1), object(2)
memory usage: 23.6+ KB

In [118]:
# Create a "first_name" and "last_name" column with the first and last names from the "name" column. 
contact_info[['first_name','last_name']] = contact_info['name'].str.split(' ',expand=True)

# Drop the contact_name column
contact_info = contact_info.drop(['name'], axis=1)
contact_info.head()

   contact_id                         email first_name last_name
0        4661  cecilia.velasco@rodrigues.fr    Cecilia   Velasco
1        3765       mariana.ellis@rossi.org    Mariana     Ellis
2        4187       sofie.woods@riviere.com      Sofie     Woods
3        4941   jeanette.iannotti@yahoo.com   Jeanette  Iannotti
4        2199      samuel.sorgatz@gmail.com     Samuel   Sorgatz

In [119]:
# Reorder the columns
contacts_df_clean = contact_info[['contact_id', 'first_name', 'last_name', 'email']]
contacts_df_clean.head()

   contact_id first_name last_name                         email
0        4661    Cecilia   Velasco  cecilia.velasco@rodrigues.fr
1        3765    Mariana     Ellis       mariana.ellis@rossi.org
2        4187      Sofie     Woods       sofie.woods@riviere.com
3        4941   Jeanette  Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel   Sorgatz      samuel.sorgatz@gmail.com

In [121]:
# Check the datatypes one more time before exporting as CSV file.
contacts_df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   contact_id  1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

In [122]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts_BChamot.csv", encoding='utf8', index=False)

### Option 2: Use regex to create the contacts DataFrame.

In [31]:
contact_info_df_copy = contact_info_df.copy()
contact_info_df_copy.head()

                                                                                contact_info
0   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
1          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
2            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
3  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}
4        {"contact_id": 2199, "name": "Samuel Sorgatz", "email": "samuel.sorgatz@gmail.com"}

In [32]:
# Extract the four-digit contact ID number.

,contact_info,contact_id
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199

In [33]:
# Check the datatypes.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   contact_info  1000 non-null   object
 1   contact_id    1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [34]:
# Convert the "contact_id" column to an int64 data type.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   contact_info  1000 non-null   object
 1   contact_id    1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [35]:
# Extract the name of the contact and add it to a new column.

,contact_info,contact_id,name
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661,Cecilia Velasco
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765,Mariana Ellis
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187,Sofie Woods
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941,Jeanette Iannotti
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199,Samuel Sorgatz
5,"{""contact_id"": 5650, ""name"": ""Socorro Luna"", ""email"": ""socorro.luna@hotmail.com""}",5650,Socorro Luna
6,"{""contact_id"": 5889, ""name"": ""Carolina Murray"", ""email"": ""carolina.murray@knight.com""}",5889,Carolina Murray
7,"{""contact_id"": 4842, ""name"": ""Kayla Moon"", ""email"": ""kayla.moon@yahoo.de""}",4842,Kayla Moon
8,"{""contact_id"": 3280, ""name"": ""Ariadna Geisel"", ""email"": ""ariadna.geisel@rangel.com""}",3280,Ariadna Geisel
9,"{""contact_id"": 5468, ""name"": ""Danielle Ladeck"", ""email"": ""danielle.ladeck@scalfaro.net""}",5468,Danielle Ladeck

In [36]:
# Extract the email from the contacts and add the values to a new column.

,contact_info,contact_id,name,email
0,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}",4661,Cecilia Velasco,cecilia.velasco@rodrigues.fr
1,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}",3765,Mariana Ellis,mariana.ellis@rossi.org
2,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}",4187,Sofie Woods,sofie.woods@riviere.com
3,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}",4941,Jeanette Iannotti,jeanette.iannotti@yahoo.com
4,"{""contact_id"": 2199, ""name"": ""Samuel Sorgatz"", ""email"": ""samuel.sorgatz@gmail.com""}",2199,Samuel Sorgatz,samuel.sorgatz@gmail.com
5,"{""contact_id"": 5650, ""name"": ""Socorro Luna"", ""email"": ""socorro.luna@hotmail.com""}",5650,Socorro Luna,socorro.luna@hotmail.com
6,"{""contact_id"": 5889, ""name"": ""Carolina Murray"", ""email"": ""carolina.murray@knight.com""}",5889,Carolina Murray,carolina.murray@knight.com
7,"{""contact_id"": 4842, ""name"": ""Kayla Moon"", ""email"": ""kayla.moon@yahoo.de""}",4842,Kayla Moon,kayla.moon@yahoo.de
8,"{""contact_id"": 3280, ""name"": ""Ariadna Geisel"", ""email"": ""ariadna.geisel@rangel.com""}",3280,Ariadna Geisel,ariadna.geisel@rangel.com
9,"{""contact_id"": 5468, ""name"": ""Danielle Ladeck"", ""email"": ""danielle.ladeck@scalfaro.net""}",5468,Danielle Ladeck,danielle.ladeck@scalfaro.net

In [37]:
# Create a copy of the contact_info_df with the 'contact_id', 'name', 'email' columns.

   contact_id               name                         email
0        4661    Cecilia Velasco  cecilia.velasco@rodrigues.fr
1        3765      Mariana Ellis       mariana.ellis@rossi.org
2        4187        Sofie Woods       sofie.woods@riviere.com
3        4941  Jeanette Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel Sorgatz      samuel.sorgatz@gmail.com
5        5650       Socorro Luna      socorro.luna@hotmail.com
6        5889    Carolina Murray    carolina.murray@knight.com
7        4842         Kayla Moon           kayla.moon@yahoo.de
8        3280     Ariadna Geisel     ariadna.geisel@rangel.com
9        5468    Danielle Ladeck  danielle.ladeck@scalfaro.net

In [38]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 


# Drop the contact_name column

   contact_id                         email first_name last_name
0        4661  cecilia.velasco@rodrigues.fr    Cecilia   Velasco
1        3765       mariana.ellis@rossi.org    Mariana     Ellis
2        4187       sofie.woods@riviere.com      Sofie     Woods
3        4941   jeanette.iannotti@yahoo.com   Jeanette  Iannotti
4        2199      samuel.sorgatz@gmail.com     Samuel   Sorgatz
5        5650      socorro.luna@hotmail.com    Socorro      Luna
6        5889    carolina.murray@knight.com   Carolina    Murray
7        4842           kayla.moon@yahoo.de      Kayla      Moon
8        3280     ariadna.geisel@rangel.com    Ariadna    Geisel
9        5468  danielle.ladeck@scalfaro.net   Danielle    Ladeck

In [39]:
# Reorder the columns

   contact_id first_name last_name                         email
0        4661    Cecilia   Velasco  cecilia.velasco@rodrigues.fr
1        3765    Mariana     Ellis       mariana.ellis@rossi.org
2        4187      Sofie     Woods       sofie.woods@riviere.com
3        4941   Jeanette  Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel   Sorgatz      samuel.sorgatz@gmail.com
5        5650    Socorro      Luna      socorro.luna@hotmail.com
6        5889   Carolina    Murray    carolina.murray@knight.com
7        4842      Kayla      Moon           kayla.moon@yahoo.de
8        3280    Ariadna    Geisel     ariadna.geisel@rangel.com
9        5468   Danielle    Ladeck  danielle.ladeck@scalfaro.net

In [40]:
# Check the datatypes one more time before exporting as CSV file.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   contact_id  1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

In [41]:
# Export the DataFrame as a CSV file. 
# contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)